language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

branches:
    only:
        - master

services:
    - elasticsearch

php:
    - 7.1
    - 7.2
    - 7.3

matrix:
    fast_finish: true

before_install:
    - phpenv config-rm xdebug.ini || true

install:
    - composer install --optimize-autoloader --no-interaction --prefer-source

script:
    - make database
    - sleep 10
    - make tests
    - make rusty
